// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPYaq0UHE7FVZ-_8J-dCju29yb4XfJto',
    appId: '1:958060924780:android:0484db72c4c3208f4ced49',
    messagingSenderId: '958060924780',
    projectId: 'delivery-app-c5c34',
    storageBucket: 'delivery-app-c5c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfCvLYkT43pPI5brgWmimsAJ-eDKeSiY',
    appId: '1:958060924780:ios:2ac28255de5ad39f4ced49',
    messagingSenderId: '958060924780',
    projectId: 'delivery-app-c5c34',
    storageBucket: 'delivery-app-c5c34.appspot.com',
    iosBundleId: 'com.example.flutterxfirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjTPXDt3aYHVg3xmRfQnuGhke3K3ITiU',
    appId: '1:958060924780:web:c90d0b3f9ba595c24ced49',
    messagingSenderId: '958060924780',
    projectId: 'delivery-app-c5c34',
    authDomain: 'delivery-app-c5c34.firebaseapp.com',
    storageBucket: 'delivery-app-c5c34.appspot.com',
    measurementId: 'G-3HTEEE38VW',
  );

}